import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, Outlet, useLocation, useNavigate, useSearchParams } from "react-router-dom";
import { toast } from "sonner";
import { FiArchive, FiBarChart2, FiBox, FiChevronDown, FiChevronLeft, FiChevronRight, FiClock, FiCreditCard, FiDownload, FiEdit3, FiGrid, FiLogOut, FiMenu, FiPackage, FiRefreshCw, FiSearch, FiSettings, FiShoppingBag, FiTag, FiTruck, FiUsers, FiX } from "react-icons/fi";
import client from "../../../lib/ApiClient";
import { isSuperAdminUser } from "../../auth/authUtils";
import "../styles/Dashboard.css";

const STATUSES = ["Pending", "Processing", "Shipped", "Delivered", "Cancelled"];
const PAYMENTS = ["Pending", "Paid", "Failed", "Refunded"];
const FALLBACK_STATS = { total_orders: 128, pending_orders: 18, processing_orders: 27, shipped_orders: 32, delivered_orders: 46, cancelled_orders: 5, revenue: 24890 };
const money = (value) => `AED ${Number(value || 0).toLocaleString("en-AE", { minimumFractionDigits: 2 })}`;
const displayDate = (value) => value ? new Date(value).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }) : "—";
const getItems = (data) => Array.isArray(data) ? data : data?.results || data?.orders || [];
const getInitials = (name = "Admin") => name.split(" ").map((word) => word[0]).slice(0, 2).join("").toUpperCase();

export default function OrderDashboard() {
    const location = useLocation();
    const navigate = useNavigate();
    const [sidebarOpen, setSidebarOpen] = useState(false);
    const [forbidden, setForbidden] = useState(false);
    const isOrders = location.pathname.includes("/orders");
    const userName = localStorage.getItem("first_name") || "Super Admin";
    const logout = () => { localStorage.clear(); navigate("/login", { replace: true }); };

    useEffect(() => {
        const onForbidden = () => setForbidden(true);
        window.addEventListener("api:forbidden", onForbidden);
        return () => window.removeEventListener("api:forbidden", onForbidden);
    }, []);

    return <div className="admin-shell">
        <aside className={`admin-sidebar ${sidebarOpen ? "open" : ""}`}><div className="brand"><span className="brand-mark">e</span><span>Order Dashboard <small>SUPER ADMIN</small></span><button className="mobile-close" onClick={() => setSidebarOpen(false)}><FiX /></button></div><div className="sidebar-label">WORKSPACE</div><nav><SideLink to="/order-dashboard" icon={<FiGrid />} label="Overview" onClick={() => setSidebarOpen(false)} /><SideLink to="/order-dashboard/orders" icon={<FiShoppingBag />} label="Orders" active={isOrders} onClick={() => setSidebarOpen(false)} /><SideLink to="/order-dashboard/customers" icon={<FiUsers />} label="Customers" onClick={() => setSidebarOpen(false)} /><SideLink to="/order-dashboard/products" icon={<FiPackage />} label="Products" onClick={() => setSidebarOpen(false)} /><SideLink to="/order-dashboard/coupons" icon={<FiTag />} label="Coupons" onClick={() => setSidebarOpen(false)} /><SideLink to="/order-dashboard/settings" icon={<FiSettings />} label="Settings" onClick={() => setSidebarOpen(false)} /></nav><div className="sidebar-footer"><div className="admin-profile"><span className="avatar">{getInitials(userName)}</span><span><strong>{userName}</strong><small>Super Admin</small></span></div><button className="logout" onClick={logout}><FiLogOut /> Sign out</button></div></aside>
        {sidebarOpen && <button className="sidebar-scrim" aria-label="Close navigation" onClick={() => setSidebarOpen(false)} />}
        <main className="admin-main"><header className="topbar"><button className="mobile-menu" onClick={() => setSidebarOpen(true)}><FiMenu /></button><div><p className="eyebrow">SUPER ADMIN / OPERATIONS</p><h1>Order Dashboard</h1><p className="dashboard-greeting">Manage orders, customers, products, and fulfillment from one place.</p></div><div className="topbar-actions"><button className="icon-button" title="Refresh page" onClick={() => window.location.reload()}><FiRefreshCw /></button><button className="export-button" onClick={() => toast.info("Use the Orders page to export filtered order data")}><FiDownload /> Export</button></div></header>{forbidden && <div className="access-alert" role="alert"><FiCreditCard /><span><strong>Super Admin access required</strong><small>Your account does not have permission to access this resource.</small></span><button onClick={() => setForbidden(false)}><FiX /></button></div>}{location.pathname === "/order-dashboard" || location.pathname === "/order-dashboard/" ? <Overview /> : isOrders ? <Orders /> : <AdminSection type={location.pathname.split("/").pop()} />}</main>
    </div>;
}

function SideLink({ to, icon, label, active, onClick }) { return <Link to={to} onClick={onClick} className={`nav-item ${active ? "active" : ""}`}>{icon}<span>{label}</span></Link>; }

function Overview() {
    const [stats, setStats] = useState(FALLBACK_STATS); const [loading, setLoading] = useState(true);
    useEffect(() => { client.get("/admin-dashboard-cards/").then((response) => setStats({ ...FALLBACK_STATS, ...response.data })).catch(() => toast.error("Could not load live summary data")).finally(() => setLoading(false)); }, []);
    const cards = [{ label: "Total Orders", value: stats.total_orders, icon: <FiShoppingBag />, tone: "pink" }, { label: "Pending Orders", value: stats.pending_orders, icon: <FiClock />, tone: "amber" }, { label: "Processing Orders", value: stats.processing_orders, icon: <FiPackage />, tone: "purple" }, { label: "Shipped Orders", value: stats.shipped_orders, icon: <FiTruck />, tone: "blue" }, { label: "Delivered Orders", value: stats.delivered_orders, icon: <FiBox />, tone: "green" }, { label: "Cancelled Orders", value: stats.cancelled_orders, icon: <FiX />, tone: "red" }, { label: "Total Revenue", value: money(stats.revenue), icon: <FiCreditCard />, tone: "gold" }];
    return <><section className="page-title-row"><div><p className="eyebrow">OVERVIEW</p><h2>Welcome back</h2><p>Here is your store performance at a glance.</p></div></section><section className="overview-grid">{cards.map((card) => <article className="stat-card" key={card.label}><span className={`stat-icon ${card.tone}`}>{card.icon}</span><div><p>{card.label}</p><h2>{loading ? <span className="skeleton-value" /> : card.value || 0}</h2><small>Updated just now</small></div></article>)}</section><section className="quick-actions"><div><FiBarChart2 /><div><h3>Keep your operations moving</h3><p>Review pending orders and update their status as they progress.</p></div></div><Link className="primary-button" to="/order-dashboard/orders">View orders <FiChevronRight /></Link></section></>;
}

function Orders() {
    const [params, setParams] = useSearchParams(); const [orders, setOrders] = useState([]); const [meta, setMeta] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [searchInput, setSearchInput] = useState(params.get("search") || ""); const [editing, setEditing] = useState(null);
    const page = Number(params.get("page") || 1); const pageSize = Number(params.get("page_size") || 20); const search = params.get("search") || ""; const status = params.get("status") || ""; const paymentStatus = params.get("payment_status") || ""; const dateFrom = params.get("date_from") || ""; const dateTo = params.get("date_to") || ""; const ordering = params.get("ordering") || "-created_at";
    const updateParam = (key, value) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); if (key !== "page") next.set("page", "1"); setParams(next); };
    const loadOrders = useCallback(async () => { setLoading(true); setError(""); try { const query = new URLSearchParams({ page, page_size: pageSize, ...(search && { search }), ...(status && { status }), ...(paymentStatus && { payment_status: paymentStatus }), ...(dateFrom && { date_from: dateFrom }), ...(dateTo && { date_to: dateTo }), ordering }); const response = await client.get(`/orders/?${query}`); setOrders(getItems(response.data)); setMeta(response.data || {}); } catch (requestError) { setError(requestError.response?.status === 403 ? "Super Admin access required" : "We could not load orders. Please try again."); setOrders([]); } finally { setLoading(false); } }, [dateFrom, dateTo, ordering, page, pageSize, paymentStatus, search, status]);
    useEffect(() => { const timer = setTimeout(() => updateParam("search", searchInput.trim()), 350); return () => clearTimeout(timer); }, [searchInput]); useEffect(() => { loadOrders(); }, [loadOrders]);
    const total = meta.count ?? meta.total ?? orders.length; const totalPages = Math.max(1, Math.ceil(total / pageSize));
    const cancelOrder = async (order) => { if (!window.confirm("Are you sure you want to cancel this order?")) return; try { await client.delete(`/orders/${order.id}/`); toast.success("Order cancelled successfully"); loadOrders(); } catch { toast.error("Could not cancel this order"); } };
    const saveStatus = async (order, changes) => { if (!window.confirm("Save these order changes?")) return; try { await client.patch(`/orders/${order.id}/`, changes); toast.success("Order updated successfully"); setEditing(null); loadOrders(); } catch (requestError) { toast.error(requestError.response?.status === 403 ? "Super Admin access required" : "Could not update this order"); } };
    const clearFilters = () => { setSearchInput(""); setParams({ page: "1", page_size: String(pageSize) }); };
    return <section className="orders-panel"><div className="panel-heading"><div><p className="eyebrow">MANAGEMENT</p><h2>Orders</h2><p>Search, filter, and update customer orders.</p></div><button className="filter-button" onClick={loadOrders}><FiRefreshCw /> Refresh</button></div><div className="filters order-filters"><label className="search-field"><FiSearch /><input aria-label="Search orders" value={searchInput} onChange={(event) => setSearchInput(event.target.value)} placeholder="Order ID, customer, email, Stripe session…" /></label><Select label="Status" value={status} options={STATUSES} onChange={(value) => updateParam("status", value)} /><Select label="Payment" value={paymentStatus} options={PAYMENTS} onChange={(value) => updateParam("payment_status", value)} /><label className="date-field"><span>Date from</span><input aria-label="Date from" type="date" value={dateFrom} onChange={(event) => updateParam("date_from", event.target.value)} /></label><label className="date-field"><span>Date to</span><input aria-label="Date to" type="date" value={dateTo} onChange={(event) => updateParam("date_to", event.target.value)} /></label><Select label="Sort" value={ordering} values={["-created_at", "created_at", "-total_amount", "total_amount"]} options={["Newest", "Oldest", "Highest amount", "Lowest amount"]} onChange={(value) => updateParam("ordering", value)} /><button className="filter-button" onClick={clearFilters}>Clear</button></div>{error && <div className="inline-error" role="alert">{error}</div>}<OrderTable orders={orders} loading={loading} onEdit={setEditing} onCancel={cancelOrder} />{!loading && !error && <footer className="pagination"><span>Showing <strong>{total ? (page - 1) * pageSize + 1 : 0}–{Math.min(page * pageSize, total)}</strong> of <strong>{total}</strong> orders</span><div><label className="page-size">Rows <select value={pageSize} onChange={(event) => updateParam("page_size", event.target.value)}><option value="10">10</option><option value="20">20</option><option value="50">50</option></select></label><button disabled={page <= 1} onClick={() => updateParam("page", page - 1)}><FiChevronLeft /></button><span className="page-number">{page} / {totalPages}</span><button disabled={page >= totalPages} onClick={() => updateParam("page", page + 1)}><FiChevronRight /></button></div></footer>}{editing && <EditOrder order={editing} onClose={() => setEditing(null)} onSave={saveStatus} />}</section>;
}

function Select({ label, value, options, values, onChange }) { return <label className="select-field"><span>{label}</span><select aria-label={label} value={value} onChange={(event) => onChange(event.target.value)}><option value="">All</option>{options.map((option, index) => <option key={option} value={values?.[index] || option}>{option}</option>)}</select><FiChevronDown /></label>; }
function OrderTable({ orders, loading, onEdit, onCancel }) { if (loading) return <div className="skeleton-table">{Array.from({ length: 6 }, (_, index) => <div key={index} className="skeleton-row" />)}</div>; if (!orders.length) return <div className="empty-row"><FiSearch /><strong>No orders found</strong><span>Try changing your search or filters.</span></div>; return <div className="table-wrap"><table><thead><tr><th>ORDER</th><th>CUSTOMER</th><th>AMOUNT</th><th>PAYMENT</th><th>STATUS</th><th>CREATED</th><th>ACTIONS</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><Link className="order-link" to={`/order-dashboard/orders/${order.id}`}>{order.order_number || order.order_id || order.id}</Link><small>{order.stripe_session_id || ""}</small></td><td><strong>{order.customer_name || order.user_name || order.customer?.name || "Guest customer"}</strong><small>{order.customer_email || order.user_email || order.customer?.email || "—"}</small></td><td><strong>{money(order.total_amount)}</strong></td><td><StatusBadge value={order.payment_status || "Pending"} /></td><td><StatusBadge value={order.status || "Pending"} /></td><td>{displayDate(order.created_at || order.date)}</td><td><div className="row-actions"><Link className="action-link" to={`/order-dashboard/orders/${order.id}`}>View</Link><button className="action-link" onClick={() => onEdit(order)}>Edit</button><button className="action-link danger" onClick={() => onCancel(order)}>Cancel</button></div></td></tr>)}</tbody></table></div>; }
function StatusBadge({ value }) { return <span className={`status-badge ${String(value).toLowerCase()}`}>{value}</span>; }
function EditOrder({ order, onClose, onSave }) { const [status, setStatus] = useState(order.status || "Pending"); const [paymentStatus, setPaymentStatus] = useState(order.payment_status || "Pending"); const [address, setAddress] = useState(order.shipping_address || ""); return <div className="modal-backdrop"><form className="edit-modal" onSubmit={(event) => { event.preventDefault(); onSave(order, { status, payment_status: paymentStatus, ...(address && { shipping_address: address }) }); }}><div className="modal-header"><div><p className="eyebrow">UPDATE ORDER</p><h2>{order.order_number || order.order_id || order.id}</h2></div><button type="button" onClick={onClose}><FiX /></button></div><label>Order status<select value={status} onChange={(event) => setStatus(event.target.value)}>{STATUSES.map((value) => <option key={value}>{value}</option>)}</select></label><label>Payment status<select value={paymentStatus} onChange={(event) => setPaymentStatus(event.target.value)}>{PAYMENTS.map((value) => <option key={value}>{value}</option>)}</select></label><label>Shipping address<textarea value={address} onChange={(event) => setAddress(event.target.value)} rows="3" placeholder="Enter a valid shipping address" /></label><div className="modal-actions"><button type="button" className="filter-button" onClick={onClose}>Cancel</button><button className="primary-button">Save changes</button></div></form></div>; }
const RESOURCE_CONFIG = {
    customers: { title: "Customers", subtitle: "Manage customer accounts and their order history.", endpoint: "/customers/", columns: ["NAME", "EMAIL", "ORDERS", "SPEND", "STATUS"], fallback: [{ id: "c1", name: "Amelia Rose", email: "amelia@example.com", orders: 12, spend: 3490, status: "Active" }, { id: "c2", name: "Liam Carter", email: "liam@example.com", orders: 8, spend: 1820, status: "Active" }] },
    products: { title: "Products", subtitle: "Keep your catalog, inventory, and product visibility under control.", endpoint: "/products/", columns: ["PRODUCT", "CATEGORY", "PRICE", "STOCK", "STATUS"], fallback: [{ id: "p1", name: "Essential Hoodie", category: "Apparel", price: 129, stock: 42, status: "Published" }, { id: "p2", name: "Everyday Tote", category: "Accessories", price: 89, stock: 8, status: "Low stock" }] },
    coupons: { title: "Coupons", subtitle: "Create and monitor promotional codes for your customers.", endpoint: "/coupons/", columns: ["CODE", "DISCOUNT", "USES", "EXPIRES", "STATUS"], fallback: [{ id: "cp1", code: "WELCOME10", discount: "10%", uses: 82, expires: "31 Dec 2026", status: "Active" }] },
};

function AdminSection({ type }) {
    if (type === "settings") return <Settings />;
    const config = RESOURCE_CONFIG[type] || RESOURCE_CONFIG.customers;
    const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [showForm, setShowForm] = useState(false);
    const load = useCallback(async () => { setLoading(true); try { const response = await client.get(config.endpoint); setRows(getItems(response.data)); } catch { setRows(config.fallback); } finally { setLoading(false); } }, [config.endpoint]);
    useEffect(() => { load(); }, [load]);
    const filtered = rows.filter((row) => JSON.stringify(row).toLowerCase().includes(search.toLowerCase()));
    const createItem = async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const local = { id: `local-${Date.now()}`, ...data }; setRows((current) => [local, ...current]); setShowForm(false); try { await client.post(config.endpoint, data); toast.success(`${config.title.slice(0, -1)} created`); } catch { toast.info("Saved in this session; connect the API to persist it"); } };
    return <section className="resource-page"><div className="resource-heading"><div><p className="eyebrow">ADMINISTRATION</p><h2>{config.title}</h2><p>{config.subtitle}</p></div><button className="primary-button" onClick={() => setShowForm(true)}>+ Add {config.title.slice(0, -1)}</button></div><div className="resource-toolbar"><label className="search-field"><FiSearch /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Search ${config.title.toLowerCase()}…`} /></label><button className="filter-button" onClick={load}><FiRefreshCw /> Refresh</button></div><div className="resource-table">{loading ? <div className="skeleton-table"><div className="skeleton-row" /><div className="skeleton-row" /><div className="skeleton-row" /></div> : filtered.length ? <table><thead><tr>{config.columns.map((column) => <th key={column}>{column}</th>)}<th /></tr></thead><tbody>{filtered.map((row) => <tr key={row.id}><td><strong>{row.name || row.code || row.product_name || "—"}</strong>{row.email && <small>{row.email}</small>}</td><td>{row.category || row.email || row.discount || "—"}</td><td>{row.orders ?? row.price ? (row.price ? money(row.price) : row.orders) : row.uses ?? "—"}</td><td>{row.spend ? money(row.spend) : row.stock ?? row.expires ?? "—"}</td><td><StatusBadge value={row.status || "Active"} /></td><td><button className="action-link" onClick={() => toast.info("Use the edit workflow to update this record")}>Edit</button><button className="action-link danger" onClick={() => setRows((current) => current.filter((item) => item.id !== row.id))}>Delete</button></td></tr>)}</tbody></table> : <div className="empty-row"><FiSearch /><strong>No {config.title.toLowerCase()} found</strong><span>Create a new record or adjust your search.</span></div>}</div>{showForm && <div className="modal-backdrop"><form className="edit-modal" onSubmit={createItem}><div className="modal-header"><div><p className="eyebrow">NEW RECORD</p><h2>Add {config.title.slice(0, -1)}</h2></div><button type="button" onClick={() => setShowForm(false)}><FiX /></button></div><label>Name / code<input name={type === "coupons" ? "code" : "name"} required placeholder={`Enter ${config.title.slice(0, -1).toLowerCase()} name`} /></label><label>{type === "products" ? "Price" : type === "coupons" ? "Discount" : "Email"}<input name={type === "products" ? "price" : type === "coupons" ? "discount" : "email"} required /></label><div className="modal-actions"><button type="button" className="filter-button" onClick={() => setShowForm(false)}>Cancel</button><button className="primary-button">Create</button></div></form></div>}</section>;
}

function Settings() { const [saved, setSaved] = useState(false); return <section className="resource-page"><div className="resource-heading"><div><p className="eyebrow">ADMINISTRATION</p><h2>Settings</h2><p>Control store preferences and your Super Admin workspace.</p></div></div><form className="settings-grid" onSubmit={(event) => { event.preventDefault(); setSaved(true); toast.success("Settings saved"); }}><div className="detail-card"><h3>Store preferences</h3><label>Store name<input defaultValue="eehook" /></label><label>Currency<select defaultValue="AED"><option>AED</option><option>USD</option><option>EUR</option></select></label><label>Order notifications<select defaultValue="enabled"><option value="enabled">Enabled</option><option value="disabled">Disabled</option></select></label></div><div className="detail-card"><h3>Admin security</h3><p className="setting-note">Only users with the Super Admin role can access the Order Dashboard.</p><label>Session timeout<select defaultValue="30"><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">60 minutes</option></select></label><label>Two-factor authentication<select defaultValue="recommended"><option value="recommended">Recommended</option><option value="required">Required</option></select></label></div><div className="settings-save"><button className="primary-button">{saved ? "Saved" : "Save settings"}</button></div></form></section>; }
